#!/usr/bin/env python

API_REQUEST_SESSION_TRACKER = 0

API_REQUEST_TRACKER = {
    "/application": 0,
    "/blueprint": 0,
    "/collection": 0,
    "/command": 0,
    "/content": 0,
    "/device/": 0,
    "/devicegroup": 0,
    "directory_record": 0,
    "/feature-flags": 0,
    "/v1/enterprise": 0,
    "/policy": 0,
    "/geofence": 0,
    "/GroupCommandsApi": 0,
    "/subscription": 0,
    "/token": 0,
    "/user": 0,
    "/wallpaper": 0,
    "OtherAPI": 0,
    "/devicetemplate": 0,
    "/itunesapps": 0,
    "/tenant-apps": 0,
}

API_FUNCTIONS = {
    "delete_app_version": "/application",
    "delete_application": "/application",
    "get_all_applications": "/application",
    "get_app_version": "/application",
    "get_app_versions": "/application",
    "get_application": "/application",
    "get_install_devices": "/application",
    "upload": "/application",
    "get_command": "/command",
    "run_command": "/command",
    "create_command": "/command",
    "get_command_request_status": "/command",
    "get_device_command_history": "/command",
    "list_command_request": "/command",
    "delete_content": "/content",
    "get_all_content": "/content",
    "get_content": "/content",
    "patch_content": "/content",
    "post_content": "/content",
    "get_all_devices": "/device/",
    "get_app_installs": "/device/",
    "get_device_app_by_id": "/device/",
    "get_device_apps": "/device/",
    "get_device_by_id": "/device/",
    "get_device_event": "/device/",
    "create_group": "/devicegroup",
    "delete_group": "/devicegroup",
    "get_all_groups": "/devicegroup",
    "get_group_by_id": "/devicegroup",
    "partial_update_group": "/devicegroup",
    "update_group": "/devicegroup",
    "get_enterprise": "/v1/enterprise",
    "partial_update_enterprise": "/v1/enterprise",
    "create_policy": "/policy",
    "delete_enterprise_policy": "/policy",
    "get_policy_by_id": "/policy",
    "list_policies": "/policy",
    "partialupdate_policy": "/policy",
    "update_policy": "/policy",
    "create_geofence": "/geofence",
    "delete_geofence": "/geofence",
    "get_all_geofences": "/geofence",
    "get_geofence": "/geofence",
    "partial_update_geofence": "/geofence",
    "update_geofence": "/geofence",
    "get_group_command": "/GroupCommandsApi",
    "run_group_command": "/GroupCommandsApi",
    "create_subscription": "/subscription",
    "delete_subscription": "/subscription",
    "get_all_subscriptions": "/subscription",
    "get_subscription": "/subscription",
    "get_token_info": "/token",
    "renew_token": "/token",
    "feature_flags": "/feature-flags",
    "authz": "/authz2/",
    "tenant-apps": "/tenant-apps",
    "itunesapps": "/itunesapps",
}
